apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    # Gowtham → read-only access
    g, Gowtham, role:readonly

    # Gokul → can sync applications
    g, Gokul, role:syncer

    # Role definitions
    p, role:readonly, applications, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow

    p, role:syncer, applications, get, *, allow
    p, role:syncer, applications, sync, *, allow
    p, role:syncer, projects, get, *, allow

  policy.default: role:readonly

