apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GowthamNirmala/argocd.git
    targetRevision: main
    path: .
    helm:
      releaseName: my-helm-app
  destination:
    server: https://kubernetes.docker.internal:6443
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

